'use strict';

const APP_VERSION = '3.1.0';
const STORAGE_KEY = 'chroniqueHuitPreuvesV31';

const MISSIONS = [
  {
    id:'martroi', title:'La statue qui n’a rien vu', place:'Place du Martroi', icon:'🐎', image:'assets/martroi.svg',
    seal:'Sceau de la mémoire', sealIcon:'🕯️', item:'Médaillon du Martroi', proof:'La statue actuelle commémore Jeanne, mais elle n’était pas présente en 1429.',
    intro:'Le Brouilleur affirme que la statue équestre a vu Jeanne entrer dans Orléans. Utilise le monument réel et les dates pour démontrer que c’est impossible.',
    essential:'m1-dates',
    stages:[
      {id:'m1-observe',type:'fieldSelect',title:'Le relevé du monument',instruction:'Fais le tour de la statue. Sélectionne uniquement les éléments que tu peux réellement observer.',options:[
        ['🐎','Un cheval'],['🛡️','Une armure'],['⚔️','Une épée'],['👑','Une couronne'],['🖼️','Des bas-reliefs sur le socle'],['📖','Un livre ouvert']
      ],correct:[0,1,2,4],hints:['Regarde d’abord Jeanne, puis le socle sous le cheval.','Deux objets proposés n’apparaissent pas sur le monument.','Écarte la couronne et le livre.'],explain:'Le cheval, l’armure, l’épée et les bas-reliefs participent au récit monumental. Jeanne n’est pas représentée comme une reine.'},
      {id:'m1-frieze',type:'order',title:'La frise du socle',instruction:'Replace ces moments dans l’ordre de la vie de Jeanne.',items:[
        ['domremy','Jeanne entend ses voix à Domrémy','🌳'],['orleans','Jeanne arrive à Orléans','🏰'],['reims','Charles VII est sacré à Reims','👑'],['rouen','Jeanne meurt à Rouen','🔥']
      ],correct:['domremy','orleans','reims','rouen'],hints:['Commence par son enfance et termine par Rouen.','Orléans vient avant le sacre de Reims.','Domrémy → Orléans → Reims → Rouen.'],explain:'Cette chronologie transforme les scènes du socle en récit historique.'},
      {id:'m1-dates',type:'sort',essential:true,title:'Le piège des dates',instruction:'Classe chaque événement dans la bonne époque.',zones:[['1429','1429'],['1855','1855'],['today','Notre visite']],items:[
        ['arrival','Jeanne entre dans Orléans','1429'],['statue','La statue actuelle est installée','1855'],['visit','Nous observons la place','today']
      ],hints:['La visite de Jeanne précède de plusieurs siècles la statue actuelle.','La date 1855 concerne le monument que tu vois.','Arrivée : 1429 ; statue : 1855 ; visite : aujourd’hui.'],explain:'La statue actuelle est installée en 1855, plus de quatre siècles après l’arrivée de Jeanne.'},
      {id:'m1-claim',type:'single',title:'Le mensonge du Brouilleur',instruction:'Quelle conclusion est historiquement correcte ?',options:[
        'La statue actuelle a réellement vu Jeanne en 1429.','La statue raconte la mémoire de Jeanne, mais elle est beaucoup plus récente.','Le cheval de bronze se souvient peut-être de Jeanne.'
      ],answer:1,hints:['Compare 1429 et 1855.','Un monument commémoratif n’est pas forcément un témoin.','Choisis la deuxième proposition.'],explain:'Une représentation peut raconter un événement sans avoir existé au moment de cet événement.'}
    ]
  },
  {
    id:'maison', title:'La maison aux trois époques', place:'Maison de Jeanne d’Arc', icon:'🏠', image:'assets/maison.svg',
    seal:'Sceau de l’authenticité', sealIcon:'🔑', item:'Clé de Jacques Boucher', proof:'Jeanne fut accueillie à cet emplacement, mais le bâtiment visible est une reconstruction moderne.',
    intro:'Le Brouilleur prétend que chaque poutre visible a été touchée par Jeanne. Distingue l’événement de 1429, la destruction et la reconstruction.',
    essential:'m2-layers',
    stages:[
      {id:'m2-facade',type:'fieldSelect',title:'L’empreinte de la façade',instruction:'Observe la façade. Quelles textures structurent principalement son apparence ?',options:[
        ['🪵','Des poutres de bois visibles'],['⬜','Des panneaux clairs entre les poutres'],['🧱','Une façade entièrement en briques rouges'],['🪨','De très grands blocs de pierre blanche']
      ],correct:[0,1],hints:['Cherche les lignes sombres et les surfaces claires.','Deux réponses suffisent.','Poutres de bois et panneaux clairs.'],explain:'Les pans de bois donnent au bâtiment son aspect caractéristique.'},
      {id:'m2-host',type:'single',title:'L’identité de l’hôte',instruction:'Qui accueillit Jeanne dans sa demeure ?',options:[
        'Jacques Boucher, trésorier du duc d’Orléans','Martin Lefort, boulanger de la ville','Pierre d’Aubigny, capitaine anglais'
      ],answer:0,hints:['Son prénom est Jacques.','Il travaillait avec les finances du duc d’Orléans.','Jacques Boucher.'],explain:'Jeanne séjourna chez Jacques Boucher après son entrée dans la ville.'},
      {id:'m2-calendar',type:'match',title:'Le calendrier du séjour',instruction:'Associe chaque repère à la bonne réponse.',sources:[
        ['arrival','Arrivée de Jeanne'],['departure','Fin du séjour indiqué'],['months','Le séjour traverse…']
      ],targets:[['29a','29 avril 1429'],['9m','9 mai 1429'],['two','deux mois'],['one','un seul mois']],correct:{arrival:'29a',departure:'9m',months:'two'},hints:['L’arrivée a lieu à la fin d’avril.','La fin du séjour se situe au début de mai.','29 avril ; 9 mai ; deux mois.'],explain:'Le séjour commence le 29 avril et se poursuit jusqu’au 9 mai : il traverse donc avril et mai.'},
      {id:'m2-layers',type:'sort',essential:true,title:'Les trois couches de vérité',instruction:'Classe les informations selon leur statut.',zones:[['event','Événement de 1429'],['destruction','Destruction'],['rebuild','Reconstruction'],['unproven','Affirmation non prouvée']],items:[
        ['hosted','Jeanne est accueillie dans la demeure de Jacques Boucher','event'],['war','Le bâtiment est détruit en 1940','destruction'],['sixties','La maison visible est reconstruite au XXe siècle','rebuild'],['touch','Ces poutres ont forcément été touchées par Jeanne','unproven']
      ],hints:['Un lieu peut être authentique par son histoire sans conserver chaque matériau ancien.','La phrase sur les poutres va dans “non prouvée”.','1429 / 1940 / reconstruction / affirmation non prouvée.'],explain:'Le lieu conserve la mémoire d’un séjour réel, mais le bâtiment actuel est une reconstruction.'}
    ]
  },
  {
    id:'loire', title:'Le pont perdu de la Loire', place:'Rue Royale et bords de Loire', icon:'🌊', image:'assets/loire.svg',
    seal:'Sceau du passage', sealIcon:'🌉', item:'Clé du passage de Loire', proof:'Le fleuve et le passage du pont structurent le siège, mais le pont actuel n’est pas le pont médiéval.',
    intro:'Le Brouilleur a retourné la carte et déplacé les défenses. Reconstitue la géographie du siège à partir de la Loire et des deux rives.',
    essential:'m3-map',
    stages:[
      {id:'m3-map',type:'map',essential:true,title:'Orienter le champ de bataille',instruction:'Face à la Loire, replace les trois éléments sur une carte simplifiée.',slots:[
        ['north','Rive nord : ville d’Orléans',{left:'38%',top:'9%'}],['center','Fleuve',{left:'39%',top:'46%'}],['south','Rive sud : fort des Tourelles',{left:'37%',top:'73%'}]
      ],tokens:[['city','Ville d’Orléans','north','🏘️'],['river','Loire','center','🌊'],['fort','Fort des Tourelles','south','🏯']],hints:['La ville ancienne est au nord du fleuve.','Le fort des Tourelles défendait l’extrémité sud du passage.','Ville au nord, Loire au centre, Tourelles au sud.'],explain:'Cette disposition explique pourquoi le contrôle du pont et du fort des Tourelles était stratégique.'},
      {id:'m3-bridge',type:'single',title:'Le pont ancien ou le pont actuel ?',instruction:'Observe le pont visible. Quelle description lui correspond le mieux ?',options:[
        'Un pont actuel aux arches régulières, sans fort au milieu','Un étroit pont médiéval fortifié avec portes et ouvrages défensifs','Une passerelle en bois sans arches'
      ],answer:0,hints:['Compare les arches et l’absence de fortification visible.','Le pont actuel est régulier et dégagé.','Choisis la première description.'],explain:'Le pont visible aujourd’hui n’est pas exactement celui du siège de 1429.'},
      {id:'m3-convoy',type:'match',title:'Le convoi impossible',instruction:'Choisis le moyen de passage le plus logique pour chaque convoi.',sources:[
        ['message','Messager léger et urgent'],['cart','Chariot de nourriture'],['troops','Groupe de soldats']
      ],targets:[['boat','Petite barque discrète'],['bridge','Pont principal organisé'],['wait','Attendre plusieurs jours']],correct:{message:'boat',cart:'bridge',troops:'bridge'},hints:['Un chariot ne tient pas dans une petite barque.','Les soldats ont intérêt à rester groupés.','Messager : barque ; chariot et soldats : pont.'],explain:'La logistique dépend du poids, du nombre de personnes, de l’urgence et du risque.'},
      {id:'m3-functions',type:'multi',title:'Défendre ou décorer ?',instruction:'Sélectionne les trois fonctions stratégiques d’un passage sur la Loire.',options:[
        'Transporter des vivres','Faire passer des soldats','Surveiller l’accès','Décorer le fleuve pour les fêtes'
      ],correct:[0,1,2],hints:['Une proposition n’a aucun rôle militaire ou logistique.','Écarte la décoration.','Vivres, soldats, surveillance.'],explain:'Le pont est à la fois une voie de ravitaillement, de mouvement et de contrôle.'}
    ]
  },
  {
    id:'cathedrale', title:'Les dix fenêtres de lumière', place:'Cathédrale Sainte-Croix', icon:'⛪', image:'assets/cathedrale.svg',
    seal:'Sceau de la chronologie', sealIcon:'🪟', item:'Fragment de vitrail lumineux', proof:'Les vitraux racontent la vie de Jeanne en images et permettent de reconstruire sa chronologie.',
    intro:'Le Brouilleur a mélangé les scènes des vitraux. Observe la série consacrée à Jeanne et restaure le récit de sa vie.',
    essential:'m4-order',
    stages:[
      {id:'m4-find',type:'fieldSelect',title:'Trouver la série',instruction:'Dans le calme, confirme les indices qui t’ont permis d’identifier la série de vitraux sur Jeanne.',options:[
        ['🪟','Plusieurs fenêtres racontent des scènes successives'],['🛡️','Jeanne apparaît avec des attributs guerriers'],['🚀','Une fusée apparaît dans chaque scène'],['👥','Les personnages et décors changent selon les épisodes']
      ],correct:[0,1,3],hints:['Cherche ce qui se répète et ce qui change.','La fusée est un anachronisme.','Fenêtres successives, attributs de Jeanne, scènes différentes.'],explain:'Une série de vitraux fonctionne comme un récit séquentiel.'},
      {id:'m4-signature',type:'multi',title:'La signature de Jeanne',instruction:'Quels attributs permettent souvent de reconnaître Jeanne dans ces scènes ?',options:[
        'Une armure','Une bannière','Une couronne portée comme une reine','Des soldats autour d’elle'
      ],correct:[0,1,3],hints:['Jeanne participe au sacre, mais elle n’est pas reine.','Écarte la couronne.','Armure, bannière et parfois soldats.'],explain:'Les artistes utilisent des attributs reconnaissables pour identifier Jeanne.'},
      {id:'m4-order',type:'order',essential:true,title:'La chronologie lumineuse',instruction:'Replace les grands épisodes dans l’ordre.',items:[
        ['voices','Les voix à Domrémy','🌳'],['orleans','Arrivée et combats d’Orléans','🏰'],['reims','Sacre de Charles VII à Reims','👑'],['rouen','Procès et mort à Rouen','🔥']
      ],correct:['voices','orleans','reims','rouen'],hints:['L’enfance vient avant les combats.','Le sacre suit Orléans.','Domrémy → Orléans → Reims → Rouen.'],explain:'Les vitraux permettent de lire une chronologie, pas seulement d’admirer des couleurs.'},
      {id:'m4-date',type:'single',title:'La date cachée',instruction:'Jeanne entre le 29 avril, les Tourelles sont reprises le 7 mai, puis elle vient prier après la levée du siège. Quelle date associer à sa venue dans la cathédrale ?',options:['29 avril','7 mai','8 mai'],answer:2,hints:['Il faut choisir la date qui suit les combats des Tourelles.','La levée du siège est célébrée le 8 mai.','8 mai.'],explain:'Le 8 mai est devenu une date centrale de la mémoire johannique d’Orléans.'},
      {id:'m4-puzzle',type:'rotatePuzzle',title:'Restaurer le vitrail',instruction:'Touche les neuf pièces pour les remettre droites et faire circuler la lumière.',hints:['Chaque toucher fait pivoter une pièce d’un quart de tour.','Observe la position de l’étoile centrale.','Toutes les pièces doivent retrouver la même orientation.'],explain:'Le vitrail restauré symbolise le récit remis dans le bon ordre.'}
    ]
  },
  {
    id:'groslot', title:'Le palais impossible', place:'Hôtel Groslot', icon:'🏛️', image:'assets/groslot.svg',
    seal:'Sceau du temps', sealIcon:'⏳', item:'Fleur de lys du souvenir', proof:'L’Hôtel Groslot est postérieur de plus d’un siècle à Jeanne, même s’il entretient sa mémoire.',
    intro:'Le Brouilleur affirme que Jeanne a dormi dans cette demeure. Les dates du bâtiment vont te permettre de détecter cet anachronisme.',
    essential:'m5-timeline',
    stages:[
      {id:'m5-observe',type:'fieldSelect',title:'La carte d’identité du bâtiment',instruction:'Observe l’Hôtel Groslot et sélectionne les éléments visibles ou cohérents avec sa façade.',options:[
        ['🧱','Des briques rouges'],['🪟','De grandes fenêtres'],['🎨','Un décor de demeure Renaissance'],['🏯','Des remparts de forteresse'],['🗿','Des représentations liées à Jeanne']
      ],correct:[0,1,2,4],hints:['Ce bâtiment est une demeure urbaine, pas une forteresse.','Écarte les remparts.','Briques, fenêtres, décor Renaissance et mémoire de Jeanne.'],explain:'L’architecture permet déjà de distinguer l’Hôtel Groslot d’une fortification du siège.'},
      {id:'m5-timeline',type:'order',essential:true,title:'La ligne du temps',instruction:'Place les trois repères dans l’ordre.',items:[
        ['arrival','Jeanne entre à Orléans — 1429','⚔️'],['begin','Début de construction — 1549','🧱'],['end','Fin de construction — 1558','🏛️']
      ],correct:['arrival','begin','end'],hints:['Jeanne vient plus d’un siècle avant la construction.','1549 précède 1558.','1429 → 1549 → 1558.'],explain:'Le bâtiment ne pouvait pas accueillir Jeanne pendant le siège puisqu’il n’existait pas encore.'},
      {id:'m5-gap',type:'single',title:'Plus ou moins d’un siècle ?',instruction:'Entre 1429 et 1549, l’écart est-il inférieur ou supérieur à cent ans ?',options:['Inférieur à cent ans','Exactement cent ans','Supérieur à cent ans'],answer:2,hints:['De 1429 à 1529, il y a déjà cent ans.','Il reste encore vingt ans jusqu’en 1549.','L’écart est de 120 ans.'],explain:'La construction commence 120 ans après l’arrivée de Jeanne.'},
      {id:'m5-enter',type:'sort',title:'Qui peut entrer ?',instruction:'Classe ces éléments selon ce que le bâtiment peut réellement contenir.',zones:[['cannot','Ne peut pas entrer en 1429'],['memory','Peut entrer dans la mémoire du lieu']],items:[
        ['jeanne','Jeanne elle-même pendant le siège','cannot'],['statue','Une statue créée plus tard','memory'],['memory','Le souvenir de Jeanne','memory']
      ],hints:['Le bâtiment n’existe pas en 1429.','Les œuvres et les souvenirs peuvent être ajoutés plus tard.','Jeanne en 1429 : impossible ; statue et mémoire : possible.'],explain:'Un lieu de mémoire peut accueillir des représentations postérieures sans être un lieu fréquenté par le personnage.'},
      {id:'m5-tri',type:'sort',title:'Histoire, mémoire ou anachronisme ?',instruction:'Classe les trois affirmations.',zones:[['history','Histoire'],['memory','Mémoire'],['anach','Anachronisme']],items:[
        ['entry','Jeanne entre dans Orléans en 1429','history'],['works','Des œuvres plus tardives représentent Jeanne','memory'],['sleep','Jeanne dort à l’Hôtel Groslot pendant le siège','anach']
      ],hints:['Une seule phrase mélange deux époques incompatibles.','Le sommeil à l’Hôtel Groslot est impossible.','Entrée : histoire ; œuvres : mémoire ; nuitée : anachronisme.'],explain:'Distinguer ces trois catégories est au cœur du travail historique.'}
    ]
  },
  {
    id:'campo', title:'Le code des arches', place:'Campo Santo', icon:'🏺', image:'assets/campo.svg',
    seal:'Sceau de l’architecture', sealIcon:'🏛️', item:'Jeton du passage silencieux', proof:'Les arches, piliers, répétitions et ombres permettent de lire l’organisation d’un ancien espace funéraire.',
    intro:'Le Brouilleur a effacé la moitié d’un plan. Utilise les formes et les répétitions du Campo Santo pour le reconstruire.',
    essential:'m6-mirror',
    stages:[
      {id:'m6-arch',type:'single',title:'Choisir l’arche réelle',instruction:'Observe une ouverture de la galerie. Quelle silhouette s’en rapproche le plus ?',options:['Un arc arrondi ou légèrement brisé','Un rectangle sans courbe','Un cercle complet posé au sol'],answer:0,hints:['Regarde le sommet de l’ouverture.','L’ouverture n’est ni un rectangle simple ni un cercle complet.','Choisis la première silhouette.'],explain:'Une arche répartit les forces et crée une ouverture répétée dans la galerie.'},
      {id:'m6-mirror',type:'singleVisual',essential:true,title:'La moitié manquante',instruction:'Choisis la moitié qui reconstitue la symétrie de l’arcade.',visuals:[
        ['A','╭│','La courbe rejoint correctement le sommet'],['B','╲│','La ligne coupe l’arche'],['C','○│','Un cercle apparaît sans continuité']
      ],answer:0,hints:['Cherche la continuité de la courbe.','Le sommet doit être symétrique.','La proposition A complète l’arche.'],explain:'La symétrie permet de reconstituer une partie manquante de l’architecture.'},
      {id:'m6-pattern',type:'match',title:'Les motifs architecturaux',instruction:'Complète les deux suites.',sources:[
        ['stone','pilier — arche — pilier — arche — ?'],['light','ombre — lumière — ombre — lumière — ?']
      ],targets:[['pillar','pilier'],['arch','arche'],['shadow','ombre'],['light','lumière']],correct:{stone:'pillar',light:'shadow'},hints:['Chaque suite alterne entre deux éléments.','Après arche vient pilier ; après lumière vient ombre.','pilier et ombre.'],explain:'Les répétitions architecturales et lumineuses créent un rythme visuel.'},
      {id:'m6-memory',type:'memorySequence',title:'La mémoire du passage',instruction:'Mémorise les quatre symboles, puis remets-les dans l’ordre demandé : ce qui soutient, ce qui ouvre, la lumière, l’ombre.',sequence:[['pillar','▥','Pilier'],['arch','∩','Arche'],['light','☀','Lumière'],['shadow','◐','Ombre']],correct:['pillar','arch','light','shadow'],hints:['“Ce qui soutient” désigne le pilier.','“Ce qui ouvre” désigne l’arche.','Pilier → arche → lumière → ombre.'],explain:'Observer un lieu, c’est aussi mémoriser l’ordre de ses formes et de ses contrastes.'},
      {id:'m6-use',type:'single',title:'L’usage du lieu',instruction:'Quel usage correspond le mieux à l’histoire du Campo Santo ?',options:['Un ancien espace funéraire','Une gare médiévale','Un port de la Loire','Une forteresse royale'],answer:0,hints:['Le nom “Campo Santo” renvoie à un espace sacré lié aux morts.','Ce n’est ni un port ni une gare.','Un ancien espace funéraire.'],explain:'Le Campo Santo correspond à l’ancien grand cimetière situé près de la cathédrale.'}
    ]
  },
  {
    id:'train', title:'La carte des éclaireurs', place:'Petit train touristique', icon:'🚂', image:'assets/train.svg',
    seal:'Sceau du cartographe', sealIcon:'🗺️', item:'Bannière des éclaireurs', proof:'Les monuments forment un système spatial : Loire au sud, cathédrale et Hôtel Groslot proches, Martroi et Maison de Jeanne à l’ouest.',
    intro:'Le Brouilleur veut déplacer les monuments. Observe la ville pendant le trajet, puis reconstitue une carte mentale cohérente.',
    essential:'m7-map',
    stages:[
      {id:'m7-collect',type:'collect',title:'Collecte pendant le trajet',instruction:'Touche une carte uniquement lorsque tu reconnais réellement le lieu depuis le petit train.',items:[
        ['martroi','Statue du Martroi','🐎'],['maison','Maison de Jeanne','🏠'],['cathedrale','Cathédrale','⛪'],['groslot','Hôtel Groslot','🏛️'],['loire','Loire ou pont','🌊']
      ],required:4,hints:['Regarde surtout la ville, pas l’écran.','Quatre lieux reconnus suffisent pour continuer.','L’adulte peut valider si un monument est masqué ou si le circuit change.'],explain:'La reconnaissance à distance utilise les formes, les couleurs et la position relative des monuments.'},
      {id:'m7-riddles',type:'match',title:'Les énigmes du guide',instruction:'Associe chaque énigme à son lieu.',sources:[
        ['river','Je suis un fleuve au sud du centre ancien.'],['towers','J’ai deux grandes tours et des vitraux sur Jeanne.'],['bricks','Je suis une demeure Renaissance en briques rouges.'],['host','Je rappelle le lieu où Jeanne fut accueillie.']
      ],targets:[['loire','La Loire'],['cathedral','La cathédrale'],['groslot','L’Hôtel Groslot'],['house','La Maison de Jeanne']],correct:{river:'loire',towers:'cathedral',bricks:'groslot',host:'house'},hints:['Utilise les détails observés dans les missions précédentes.','Les briques rouges désignent l’Hôtel Groslot.','Loire / cathédrale / Hôtel Groslot / Maison de Jeanne.'],explain:'Les caractéristiques architecturales deviennent des repères d’orientation.'},
      {id:'m7-map',type:'map',essential:true,title:'Reconstituer le plan',instruction:'Replace les cinq repères sur une carte simplifiée.',slots:[
        ['martroiSlot','Martroi',{left:'15%',top:'18%'}],['houseSlot','Maison de Jeanne',{left:'10%',top:'48%'}],['cathedralSlot','Cathédrale',{left:'60%',top:'28%'}],['groslotSlot','Hôtel Groslot',{left:'66%',top:'52%'}],['loireSlot','Loire',{left:'39%',top:'79%'}]
      ],tokens:[
        ['martroi','Martroi','martroiSlot','🐎'],['house','Maison de Jeanne','houseSlot','🏠'],['cathedral','Cathédrale','cathedralSlot','⛪'],['groslot','Hôtel Groslot','groslotSlot','🏛️'],['loire','Loire','loireSlot','🌊']
      ],hints:['La Loire se place en bas de la carte.','Cathédrale et Hôtel Groslot sont proches l’un de l’autre.','Martroi au nord-ouest, Maison à l’ouest, cathédrale à l’est, Groslot près d’elle, Loire au sud.'],explain:'La carte mentale relie les étapes séparées en un seul territoire cohérent.'},
      {id:'m7-layers',type:'sort',title:'La ville de 1429 ou la ville d’après ?',instruction:'Classe les éléments dans la bonne catégorie.',zones:[['nature','Élément naturel déjà présent'],['linked','Lieu ou événement lié à 1429'],['later','Monument construit plus tard']],items:[
        ['river','La Loire','nature'],['boucher','La demeure de Jacques Boucher','linked'],['sitecat','Le site religieux de Sainte-Croix','linked'],['statue','La statue actuelle du Martroi','later'],['groslot','L’Hôtel Groslot','later']
      ],hints:['La Loire est plus ancienne que tous les monuments.','La statue et l’Hôtel Groslot sont postérieurs à Jeanne.','Loire / lieux liés à 1429 / monuments plus tardifs.'],explain:'Un site peut être ancien tout en ayant changé d’apparence au fil des siècles.'}
    ]
  },
  {
    id:'cabu', title:'Le portrait qui ne l’a jamais rencontrée', place:'Hôtel Cabu', icon:'🖼️', image:'assets/cabu.svg',
    seal:'Sceau de l’enquête historique', sealIcon:'🔍', item:'Portrait témoin du XVIe siècle', proof:'Le portrait de 1581 renseigne sur la mémoire de Jeanne au XVIe siècle, pas sur son apparence exacte en 1429.',
    intro:'Le Brouilleur affirme que Jeanne a posé devant le peintre. Observe l’œuvre et compare les dates pour tester cette affirmation.',
    essential:'m8-proof',
    stages:[
      {id:'m8-find',type:'fieldSelect',title:'Retrouver le portrait',instruction:'Devant la représentation de Jeanne, confirme ce que tu peux observer directement.',options:[
        ['🛡️','Une armure ou un vêtement guerrier'],['🎨','Des couleurs choisies par l’artiste'],['🧑‍🎨','Le peintre visible en train de travailler'],['🏳️','Un attribut ou symbole lié à Jeanne']
      ],correct:[0,1,3],hints:['Ne sélectionne que ce qui apparaît dans l’œuvre.','Le peintre n’est pas représenté en train de peindre.','Armure, couleurs et attributs.'],explain:'L’observation décrit l’image sans encore conclure sur sa vérité historique.'},
      {id:'m8-visible',type:'sort',title:'Observation ou interprétation ?',instruction:'Classe ce que l’image permet de voir et ce qu’elle ne permet pas de prouver seule.',zones:[['visible','Ce que je peux voir'],['unproven','Ce que je ne peux pas prouver avec l’image seule']],items:[
        ['armor','Jeanne est représentée en armure','visible'],['colors','L’artiste utilise certaines couleurs','visible'],['exactarmor','Jeanne portait exactement cette armure','unproven'],['face','Son visage était exactement ainsi','unproven'],['pose','Elle a posé devant le peintre','unproven']
      ],hints:['Décrire l’image n’est pas la même chose que prouver la réalité.','Le visage exact et la pose ne sont pas démontrés.','Armure représentée et couleurs : visibles ; le reste : non prouvé.'],explain:'L’historien sépare l’observation de l’interprétation.'},
      {id:'m8-dates',type:'order',title:'Le témoin impossible',instruction:'Place ces repères dans l’ordre.',items:[
        ['arrival','Jeanne à Orléans — 1429','⚔️'],['portrait','Portrait — 1581','🖼️'],['bourdelle','Œuvre de Bourdelle — 1910','🗿']
      ],correct:['arrival','portrait','bourdelle'],hints:['Le portrait est créé plus d’un siècle après Jeanne.','1910 est le repère le plus récent.','1429 → 1581 → 1910.'],explain:'Le peintre de 1581 ne pouvait pas observer Jeanne vivante.'},
      {id:'m8-representations',type:'order',title:'Les images changent avec le temps',instruction:'Classe les représentations de la plus ancienne à la plus récente.',items:[
        ['banner','Bannière du XVIe siècle','🏳️'],['portrait','Portrait de 1581','🖼️'],['bronze','Bronze de Bourdelle de 1910','🗿']
      ],correct:['banner','portrait','bronze'],hints:['La bannière et le portrait appartiennent au XVIe siècle.','Le bronze date du XXe siècle.','Bannière → portrait → bronze.'],explain:'Chaque époque réinvente en partie l’image de Jeanne.'},
      {id:'m8-proof',type:'multi',essential:true,title:'Que prouve réellement le portrait ?',instruction:'Sélectionne les deux conclusions justifiées.',options:[
        'Il montre exactement le visage de Jeanne.','Il montre comment le XVIe siècle voulait représenter Jeanne.','Il prouve que Jeanne a visité l’Hôtel Cabu.','Il témoigne de l’importance durable de sa mémoire.'
      ],correct:[1,3],hints:['Le tableau est postérieur de plus d’un siècle à Jeanne.','Il renseigne surtout sur la mémoire, pas sur une pose réelle.','Choisis les propositions 2 et 4.'],explain:'Le portrait est une source sur la mémoire de Jeanne au XVIe siècle, non un portrait d’après nature.'}
    ]
  }
];



const STAGE_SELECTION = {
  martroi:['m1-frieze','m1-dates'],
  maison:['m2-calendar','m2-layers'],
  loire:['m3-map','m3-convoy'],
  cathedrale:['m4-order','m4-puzzle'],
  groslot:['m5-timeline','m5-tri'],
  campo:['m6-mirror','m6-pattern'],
  train:['m7-collect','m7-map'],
  cabu:['m8-visible','m8-dates']
};

const TRANSITIONS = [
  {name:'Maison de Jeanne d’Arc',address:'3 place du Général-de-Gaulle, 45000 Orléans',walk:'Environ 5 minutes à pied',image:'assets/maison.svg',clue:'Le Brouilleur affirme que chaque poutre a été touchée par Jeanne. Cherche les dates qui permettront de distinguer le séjour de 1429 et la reconstruction moderne.'},
  {name:'Bords de Loire — pont George-V',address:'Place du Châtelet puis quai du Châtelet, 45000 Orléans',walk:'Environ 10 minutes à pied',image:'assets/loire.svg',clue:'La prochaine preuve se trouve dans la géographie de la ville. Observe les deux rives et demande-toi comment un message ou un chariot pouvait franchir la Loire.'},
  {name:'Cathédrale Sainte-Croix',address:'Place Sainte-Croix, 45000 Orléans',walk:'Environ 10 minutes à pied depuis les quais',image:'assets/cathedrale.svg',clue:'Le Brouilleur a mélangé les scènes de la vie de Jeanne. Les vitraux de la cathédrale devront être lus comme une bande dessinée lumineuse.'},
  {name:'Hôtel Groslot',address:'2 place de l’Étape, 45000 Orléans',walk:'Moins de 2 minutes à pied',image:'assets/groslot.svg',clue:'Une demeure en briques rouges conserve le souvenir de Jeanne… mais a-t-elle réellement pu l’accueillir en 1429 ? Les dates trancheront.'},
  {name:'Campo Santo',address:'Rue Fernand-Rabier, 45000 Orléans',walk:'Environ 3 minutes à pied',image:'assets/campo.svg',clue:'Le prochain code n’est pas écrit avec des lettres. Il est caché dans la répétition, la symétrie et le rythme des arches.'},
  {name:'Petit train touristique',address:'Départ devant l’Office de tourisme, 23 place du Martroi, 45000 Orléans',walk:'Environ 8 minutes à pied',image:'assets/train.svg',clue:'Tu vas devenir cartographe. Pendant le trajet, reconnais les monuments déjà visités et mémorise leur position dans la ville.'},
  {name:'Hôtel Cabu — musée d’Histoire et d’Archéologie',address:'Square Abbé-Desnoyers, 45000 Orléans',walk:'Environ 7 minutes à pied après le petit train',image:'assets/cabu.svg',clue:'Le Brouilleur présente un portrait comme un témoin direct. Observe l’œuvre, puis compare sa date avec 1429 pour découvrir ce qu’elle peut vraiment prouver.'}
];
const FINAL_STAGES = [
  {id:'f-anach',type:'multi',title:'Le procès des anachronismes',instruction:'Sélectionne exactement les trois affirmations fausses.',options:[
    'La statue actuelle du Martroi a vu Jeanne entrer dans Orléans.','Jeanne a été accueillie dans la demeure de Jacques Boucher.','Jeanne a dormi dans l’Hôtel Groslot.','Le pont visible aujourd’hui est exactement le pont médiéval du siège.','Des vitraux de la cathédrale racontent la vie de Jeanne.','Les habitants ont continué à représenter Jeanne longtemps après sa mort.'
  ],correct:[0,2,3],hints:['Cherche les monuments construits après 1429.','La statue, l’Hôtel Groslot et le pont actuel sont les pièges.','Sélectionne les affirmations 1, 3 et 4.'],explain:'Tu as éliminé les trois anachronismes majeurs du Brouilleur.'},
  {id:'f-time',type:'order',title:'La chronologie du siège',instruction:'Replace les événements entre l’arrivée de Jeanne et la levée du siège.',items:[
    ['entry','29 avril : Jeanne entre à Orléans','🐎'],['stloup','4 mai : prise de Saint-Loup','🏯'],['tourelles','7 mai : reprise des Tourelles','🌉'],['lift','8 mai : levée du siège','🎉']
  ],correct:['entry','stloup','tourelles','lift'],hints:['Commence par le 29 avril et termine par le 8 mai.','Saint-Loup précède les Tourelles.','29 avril → 4 mai → 7 mai → 8 mai.'],explain:'La séquence finale permet de comprendre la rapidité des événements.'},
  {id:'f-sources',type:'sort',title:'Histoire, trace ou mémoire ?',instruction:'Classe chaque élément comme le ferait une historienne.',zones:[['history','Histoire de 1429'],['trace','Trace ou lieu lié à l’événement'],['memory','Mémoire construite plus tard']],items:[
    ['arrival','L’arrivée de Jeanne','history'],['fights','Les combats autour d’Orléans','history'],['site','L’emplacement de la demeure de Jacques Boucher','trace'],['river','La Loire et la géographie du siège','trace'],['statue','La statue actuelle du Martroi','memory'],['portrait','Le portrait de 1581','memory']
  ],hints:['Les événements sont dans “histoire”.','Les sites et le fleuve sont des traces ; statue et portrait relèvent de la mémoire.','Arrivée/combat ; emplacement/Loire ; statue/portrait.'],explain:'Une enquête solide combine événements, traces matérielles et mémoires postérieures.'},
  {id:'f-sentence',type:'order',title:'La phrase restaurée',instruction:'Remets les six fragments dans l’ordre pour restaurer la Chronique.',items:[
    ['a','Jeanne d’Arc','⚔️'],['b','entre à Orléans','🏰'],['c','le 29 avril 1429.','📅'],['d','Elle participe aux combats.','🛡️'],['e','Le siège est levé','🎉'],['f','le 8 mai 1429.','📜']
  ],correct:['a','b','c','d','e','f'],hints:['Commence par le personnage, son action et la date.','La participation aux combats vient avant la levée du siège.','Jeanne → entre → 29 avril → combats → siège levé → 8 mai.'],explain:'La Chronique est restaurée : l’arrivée, les combats et la levée du siège sont correctement reliés.'}
];

const defaultState = () => ({
  version:APP_VERSION,name:'',littleName:'',hasLittle:false,started:false,prologueSeen:false,
  speech:false,contrast:'normal',reducedMotion:false,fatigue:false,
  completed:[],missionStage:{},missionStats:{},hints:{},attempts:{},proofs:[],seals:[],items:[],
  activeMission:0,finalUnlocked:false,finalStage:0,finalDone:false,createdAt:new Date().toISOString()
});

let state = loadState();
let currentScreen = 'home';
let gameUI = {};
let deferredInstallPrompt = null;

const app = document.querySelector('#app');
const subtitle = document.querySelector('#subtitle');
const bottomNav = document.querySelector('#bottomNav');
const settingsDialog = document.querySelector('#settingsDialog');
const adultDialog = document.querySelector('#adultDialog');
const confirmDialog = document.querySelector('#confirmDialog');

function loadState(){
  try{
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');
    return {...defaultState(),...saved,missionStage:{...(saved.missionStage||{})},missionStats:{...(saved.missionStats||{})},hints:{...(saved.hints||{})},attempts:{...(saved.attempts||{})}};
  }catch{return defaultState();}
}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));applySettings();}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function exactArray(a,b){return a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i]);}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function missionById(id){return MISSIONS.find(m=>m.id===id);}
function isMissionUnlocked(index){return index===0||state.completed.includes(MISSIONS[index-1].id)||state.completed.includes(MISSIONS[index].id)||state.activeMission===index;}
function effectiveStages(mission){const ids=STAGE_SELECTION[mission.id]||mission.stages.slice(0,2).map(s=>s.id);const selected=ids.map(id=>mission.stages.find(s=>s.id===id)).filter(Boolean).slice(0,2);return state.fatigue?selected.slice(0,1):selected;}
function stageKey(prefix,id){return `${prefix}:${id}`;}
function recordAttempt(prefix,stageId,correct){const key=stageKey(prefix,stageId);state.attempts[key]=(state.attempts[key]||0)+1;if(correct){const ms=state.missionStats[prefix]||{correctFirst:0,total:0,hints:0};ms.total+=1;if(state.attempts[key]===1)ms.correctFirst+=1;state.missionStats[prefix]=ms;}saveState();}
function hintCount(prefix,stageId){return state.hints[stageKey(prefix,stageId)]||0;}
function useHint(prefix,stage){const key=stageKey(prefix,stage.id);const n=Math.min((state.hints[key]||0)+1,stage.hints?.length||0);state.hints[key]=n;if(prefix!=='final'){const ms=state.missionStats[prefix]||{correctFirst:0,total:0,hints:0};ms.hints=(ms.hints||0)+1;state.missionStats[prefix]=ms;}saveState();renderHint(prefix,stage);}
function renderHint(prefix,stage){const n=hintCount(prefix,stage.id);const box=document.querySelector('#hintBox');if(!box)return;box.innerHTML=n?`<strong>Indice ${n}</strong><p>${escapeHtml(stage.hints[n-1])}</p>`:'<span class="muted">Aucun indice utilisé.</span>';const btn=document.querySelector('#hintBtn');if(btn)btn.textContent=n>=stage.hints.length?'Tous les indices affichés':`Indice ${n+1}`;if(btn)btn.disabled=n>=stage.hints.length;}
function vibrate(pattern=30){if(navigator.vibrate)navigator.vibrate(pattern);}
function toast(text){const t=document.querySelector('#toastTemplate').content.firstElementChild.cloneNode(true);t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),2800);}
function speak(text){if(!state.speech||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.94;speechSynthesis.speak(u);}
function celebrate(){vibrate([40,40,80]);const box=document.createElement('div');box.className='confetti no-print';box.setAttribute('aria-hidden','true');for(let i=0;i<22;i++){const p=document.createElement('i');p.style.left=`${Math.random()*100}%`;p.style.animationDelay=`${Math.random()*.35}s`;p.style.setProperty('--x',`${(Math.random()-.5)*160}px`);box.append(p);}document.body.append(box);setTimeout(()=>box.remove(),1700);}
function applySettings(){document.body.classList.toggle('high-contrast',state.contrast==='high');document.body.classList.toggle('reduced-motion',state.reducedMotion||matchMedia('(prefers-reduced-motion: reduce)').matches);document.querySelector('#fatigueToggle').checked=state.fatigue;document.querySelector('#speechToggle').checked=state.speech;document.querySelector('#motionToggle').checked=state.reducedMotion;document.querySelector('#contrastSelect').value=state.contrast;}
function updateNav(active=''){bottomNav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.nav===active));}
function setScreen(screen,options={}){currentScreen=screen;gameUI={};window.scrollTo({top:0,behavior:state.reducedMotion?'auto':'smooth'});bottomNav.hidden=!state.started;updateNav(['map','evidence','inventory','help'].includes(screen)?screen:'');const renderers={home:renderHome,setup:renderSetup,prologue:renderPrologue,map:renderMap,evidence:renderEvidence,inventory:renderInventory,help:renderHelp,mission:()=>renderMission(options.index??state.activeMission),reward:()=>renderReward(options.index??state.activeMission),transition:()=>renderTransition(options.index??state.activeMission),final:renderFinal,certificate:renderCertificate};(renderers[screen]||renderHome)();app.classList.remove('screen-enter');void app.offsetWidth;app.classList.add('screen-enter');app.focus({preventScroll:true});}
function appHeader(text){subtitle.textContent=text;}
function progressHeader(label,current,total){const pct=Math.round((current/total)*100);return `<div class="progress-shell"><div class="progress-label"><span>${escapeHtml(label)}</span><span>${current}/${total}</span></div><div class="progress"><span style="width:${pct}%"></span></div></div>`;}
function listenButton(text){return `<button type="button" class="ghost full listen-btn" data-speech="${escapeHtml(text)}">🔊 Écouter la narration</button>`;}
function bindSpeech(){document.querySelectorAll('[data-speech]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.speech)));}
function screenWrap(content){app.innerHTML=`<section class="screen">${content}</section>`;}

function renderHome(){
  appHeader('Enquête Jeanne d’Arc à Orléans');
  const resume=state.started?`<button id="resumeBtn" class="primary full">Reprendre l’enquête</button><button id="mapBtn" class="secondary full">Voir le parcours</button>`:`<button id="startBtn" class="primary full">Commencer l’aventure</button>`;
  screenWrap(`<article class="hero"><div class="hero-visual"><img src="assets/hero.svg" alt="Jeanne d’Arc à cheval devant une chronique et le Brouilleur d’Encre"></div><div class="hero-copy stack"><div class="eyebrow">Jeu d’enquête patrimoniale · V3.1</div><h1>La Chronique des huit preuves</h1><p class="lead">Observe les vrais lieux d’Orléans, déjoue les anachronismes du Brouilleur et restaure l’histoire de Jeanne d’Arc.</p>${resume}<div class="install-card"><span aria-hidden="true">📱</span><span><strong>100 % hors connexion après le premier chargement</strong><small>Aucun compte, aucune géolocalisation obligatoire.</small></span></div></div></article>
  <article class="card"><h2>Une enquête ancrée dans les lieux</h2><div class="grid"><div><strong>8 lieux</strong><p class="muted small">Martroi, Maison de Jeanne, Loire, cathédrale, Hôtel Groslot, Campo Santo, petit train et Hôtel Cabu.</p></div><div><strong>Plus de 35 énigmes</strong><p class="muted small">Chronologies, cartes, classements, puzzle de vitrail, mémoire et analyse d’images.</p></div><div><strong>Sans sanction</strong><p class="muted small">Trois niveaux d’indices, mode fatigue et mode adulte.</p></div></div></article>`);
  document.querySelector('#startBtn')?.addEventListener('click',()=>setScreen('setup'));
  document.querySelector('#resumeBtn')?.addEventListener('click',()=>state.finalDone?setScreen('certificate'):setScreen('map'));
  document.querySelector('#mapBtn')?.addEventListener('click',()=>setScreen('map'));
}

function renderSetup(){appHeader('Préparer la mission');screenWrap(`<article class="card stack"><div class="eyebrow">Avant de partir</div><h1 class="screen-title">Qui mène l’enquête ?</h1><form id="setupForm" class="stack"><label>Prénom de l’enquêtrice<input id="nameInput" maxlength="24" required autocomplete="given-name" value="${escapeHtml(state.name)}" placeholder="Son prénom"></label><label class="switch-row"><span><strong>Une petite éclaireuse participe</strong><small>Des missions simples seront proposées à l’enfant de 3 ans.</small></span><input id="littleToggle" type="checkbox" ${state.hasLittle?'checked':''}></label><label id="littleLabel" class="${state.hasLittle?'':'hidden'}">Prénom de la petite éclaireuse<input id="littleInput" maxlength="24" value="${escapeHtml(state.littleName)}" placeholder="Son prénom"></label><button class="primary" type="submit">Recevoir le premier message</button></form></article>`);const toggle=document.querySelector('#littleToggle');toggle.addEventListener('change',()=>document.querySelector('#littleLabel').classList.toggle('hidden',!toggle.checked));document.querySelector('#setupForm').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#nameInput').value.trim();if(!name)return toast('Indique le prénom de l’enquêtrice.');state.name=name;state.hasLittle=toggle.checked;state.littleName=toggle.checked?document.querySelector('#littleInput').value.trim():'';state.started=true;saveState();setScreen('prologue');});}

function renderPrologue(){appHeader('Prologue : l’encre qui ment');const name=escapeHtml(state.name||'Enquêtrice');screenWrap(`<article class="mission-hero hero"><img src="assets/brouilleur.svg" alt="Le Brouilleur d’Encre, créature violette tenant une plume"><div class="mission-hero-copy stack"><div class="eyebrow">Message urgent du Grand Livre</div><h1 class="screen-title">L’encre qui ment</h1><div class="brouilleur-strip"><img src="assets/brouilleur.svg" alt=""><p><strong>Le Brouilleur :</strong> « La statue a accueilli Jeanne en 1429, elle a dormi dans tous les palais et son peintre l’a rencontrée ! »</p></div><div class="character"><div class="character-avatar" aria-hidden="true">📚</div><div class="speech-bubble"><strong>Guillaume, gardien de la Chronique</strong><p>« Ne le crois pas, ${name}. Il mélange les dates, déplace les monuments et transforme les souvenirs en fausses preuves. Pour restaurer le livre, il faut vérifier l’histoire dans la ville elle-même. »</p></div></div><div class="parchment"><p><strong>Ta mission :</strong> retrouver huit Sceaux de Vérité en observant les monuments, en croisant les dates et en éliminant les affirmations impossibles.</p></div>${listenButton(`Bonjour ${state.name}. Le Brouilleur mélange les dates et les monuments. Tu devras observer les lieux réels, résoudre les énigmes et retrouver huit sceaux de vérité.`)}<button id="acceptBtn" class="primary">Je deviens Enquêtrice de la Chronique</button></div></article>`);bindSpeech();document.querySelector('#acceptBtn').addEventListener('click',()=>{state.prologueSeen=true;saveState();setScreen('map');});}

function renderMap(){appHeader('Parcours des huit preuves');const done=state.completed.length;const list=MISSIONS.map((m,i)=>{const unlocked=isMissionUnlocked(i);const status=state.completed.includes(m.id)?'done':unlocked&&i===state.activeMission?'current':unlocked?'':'locked';return `<button class="nav-card ${status}" data-mission="${i}" ${unlocked?'':'disabled'}><span class="nav-icon">${m.icon}</span><span class="nav-copy"><strong>${i+1}. ${escapeHtml(m.title)}</strong><small>${escapeHtml(m.place)}</small></span><span class="nav-status">${state.completed.includes(m.id)?'✓':unlocked?'›':'🔒'}</span></button>`}).join('');screenWrap(`<article class="card stack"><div class="mission-kicker"><div><div class="eyebrow">Carte de l’enquête</div><h1 class="screen-title">Les huit preuves</h1></div><span class="pill dark">${done}/8</span></div>${progressHeader('Sceaux authentifiés',done,8)}<p>Chaque lieu fournit une preuve différente. Les missions déjà réussies peuvent être consultées à nouveau.</p></article><div class="map-list">${list}</div>${done===8?`<article class="card center stack"><div class="seal-mark">⚖️</div><h2>Le Tribunal de la Chronique est ouvert</h2><p>Les huit preuves sont réunies. Il reste à juger les mensonges du Brouilleur.</p><button id="finalBtn" class="primary">Commencer l’épreuve finale</button></article>`:''}`);document.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>{state.activeMission=Number(b.dataset.mission);saveState();setScreen('mission',{index:state.activeMission});}));document.querySelector('#finalBtn')?.addEventListener('click',()=>{state.finalUnlocked=true;saveState();setScreen('final');});}

function renderMission(index){const mission=MISSIONS[index];if(!mission)return setScreen('map');appHeader(`${index+1}/8 · ${mission.place}`);if(state.completed.includes(mission.id)&&!gameUI.replay){screenWrap(`<article class="mission-hero card"><img src="${mission.image}" alt="Illustration de ${escapeHtml(mission.place)}"><div class="mission-hero-copy stack"><span class="pill success">Mission authentifiée</span><h1 class="screen-title">${escapeHtml(mission.title)}</h1><div class="notice success"><strong>${escapeHtml(mission.seal)}</strong><p>${escapeHtml(mission.proof)}</p></div><button id="replayBtn" class="secondary">Rejouer les énigmes</button><button id="backMap" class="primary">Retour au parcours</button></div></article>`);document.querySelector('#replayBtn').addEventListener('click',()=>{gameUI.replay=true;state.missionStage[mission.id]=0;renderMission(index)});document.querySelector('#backMap').addEventListener('click',()=>setScreen('map'));return;}
  const stages=effectiveStages(mission);let stageIndex=state.missionStage[mission.id]||0;if(stageIndex>=stages.length)return setScreen('reward',{index});const stage=stages[stageIndex];const intro=stageIndex===0?`<article class="mission-hero card"><img src="${mission.image}" alt="Illustration de ${escapeHtml(mission.place)}"><div class="mission-hero-copy stack"><div class="mission-kicker"><span class="pill">Mission ${index+1}/8</span><span class="pill dark">${escapeHtml(mission.place)}</span></div><h1 class="screen-title">${escapeHtml(mission.title)}</h1><p>${escapeHtml(mission.intro)}</p>${state.fatigue?'<div class="notice info"><strong>Mode mission courte</strong><p>Une seule épreuve essentielle est proposée dans ce lieu.</p></div>':''}${listenButton(mission.intro)}</div></article>`:'';
  screenWrap(`${intro}<article class="card stack">${progressHeader('Épreuves du lieu',stageIndex+1,stages.length)}<div class="eyebrow">Épreuve ${stageIndex+1}</div><h2>${escapeHtml(stage.title)}</h2><p>${escapeHtml(stage.instruction)}</p><div id="gameHost" class="game-board"></div><div class="hint-actions"><button id="hintBtn" type="button">Indice 1</button><button id="leaveBtn" type="button">Quitter la mission</button></div><div id="hintBox" class="hint-box"><span class="muted">Aucun indice utilisé.</span></div></article>`);bindSpeech();renderGame(mission.id,stage,()=>advanceMission(mission,index,stages));renderHint(mission.id,stage);document.querySelector('#hintBtn').addEventListener('click',()=>useHint(mission.id,stage));document.querySelector('#leaveBtn').addEventListener('click',()=>setScreen('map'));}

function advanceMission(mission,index,stages){const current=state.missionStage[mission.id]||0;state.missionStage[mission.id]=current+1;saveState();if(state.missionStage[mission.id]>=stages.length)setScreen('reward',{index});else renderMission(index);}

function renderReward(index){const m=MISSIONS[index];const stats=state.missionStats[m.id]||{correctFirst:0,total:0,hints:0};const eye='★';const historian=(stats.total&&stats.correctFirst/stats.total>=.5&&stats.hints<=2)?'★':'☆';const courage='★';screenWrap(`<article class="card reward stack"><div class="eyebrow">Preuve authentifiée</div><div class="reward-seal">${m.sealIcon}</div><h1 class="screen-title">${escapeHtml(m.seal)}</h1><p>${escapeHtml(m.proof)}</p><div class="score-row"><div class="score-box"><strong>${eye}</strong><small>Œil de lynx</small></div><div class="score-box"><strong>${historian}</strong><small>Esprit d’historienne</small></div><div class="score-box"><strong>${courage}</strong><small>Courage</small></div></div><div class="parchment"><strong>Objet ajouté</strong><p>${escapeHtml(m.item)}</p></div><button id="rewardNext" class="primary">${index===MISSIONS.length-1?'Ouvrir le Tribunal':'Découvrir la prochaine destination'}</button><button id="rewardMap" class="secondary">Voir le parcours</button></article>`);if(!state.completed.includes(m.id)){state.completed.push(m.id);state.seals.push(m.id);state.items.push(m.id);state.proofs.push(m.id);state.activeMission=Math.min(index+1,MISSIONS.length-1);if(index===MISSIONS.length-1)state.finalUnlocked=true;saveState();celebrate();}document.querySelector('#rewardNext').addEventListener('click',()=>index===MISSIONS.length-1?setScreen('final'):setScreen('transition',{index}));document.querySelector('#rewardMap').addEventListener('click',()=>setScreen('map'));}

function renderTransition(index){const t=TRANSITIONS[index];const next=MISSIONS[index+1];if(!t||!next)return setScreen('final');appHeader(`Destination suivante · ${t.name}`);const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(t.address)}`;screenWrap(`<article class="transition-card card stack"><div class="eyebrow">La quête continue</div><div class="transition-visual"><img src="${t.image}" alt="Illustration de ${escapeHtml(t.name)}"><span class="route-pulse" aria-hidden="true">➜</span></div><h1 class="screen-title">${escapeHtml(t.name)}</h1><div class="destination-details"><div><span aria-hidden="true">📍</span><p><strong>Adresse</strong><br>${escapeHtml(t.address)}</p></div><div><span aria-hidden="true">🚶</span><p><strong>Déplacement</strong><br>${escapeHtml(t.walk)}</p></div></div><div class="quest-clue"><span aria-hidden="true">🔮</span><div><strong>Indice sur la suite</strong><p>${escapeHtml(t.clue)}</p></div></div><div class="notice info"><strong>Avant de repartir</strong><p>Range le téléphone pendant la marche. Rouvre l’application lorsque tu es arrivée devant le lieu.</p></div><a class="secondary button-link full" href="${maps}" target="_blank" rel="noopener">Afficher l’itinéraire</a><button id="arrivedBtn" class="primary full">Nous sommes arrivés</button><button id="transitionMap" class="ghost full">Retour au parcours</button></article>`);document.querySelector('#arrivedBtn').addEventListener('click',()=>setScreen('mission',{index:index+1}));document.querySelector('#transitionMap').addEventListener('click',()=>setScreen('map'));}

function renderGame(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');const key=stageKey(prefix,stage.id);gameUI.key=key;switch(stage.type){
    case 'single': return gameSingle(prefix,stage,onSuccess);
    case 'singleVisual': return gameSingleVisual(prefix,stage,onSuccess);
    case 'multi':case 'fieldSelect': return gameMulti(prefix,stage,onSuccess);
    case 'order': return gameOrder(prefix,stage,onSuccess);
    case 'sort': return gameSort(prefix,stage,onSuccess);
    case 'match': return gameMatch(prefix,stage,onSuccess);
    case 'map': return gameMap(prefix,stage,onSuccess);
    case 'rotatePuzzle': return gameRotate(prefix,stage,onSuccess);
    case 'memorySequence': return gameMemorySequence(prefix,stage,onSuccess);
    case 'collect': return gameCollect(prefix,stage,onSuccess);
    default: host.innerHTML='<p>Épreuve indisponible.</p>';
  }}
function finishFeedback(prefix,stage,onSuccess,correct){recordAttempt(prefix,stage.id,correct);const fb=document.querySelector('#gameFeedback');if(!fb)return;if(correct){fb.className='feedback good';fb.innerHTML=`<h3>Preuve validée</h3><p>${escapeHtml(stage.explain)}</p><button id="gameNext" class="primary full">Continuer</button>`;document.querySelector('#gameNext').addEventListener('click',onSuccess);celebrate();}else{fb.className='feedback bad';fb.innerHTML='<h3>Le Brouilleur résiste encore</h3><p>Reprends les indices du lieu et essaie une nouvelle fois.</p>';vibrate([30,50,30]);}}
function gameSingle(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');host.innerHTML=`<div class="options-grid">${stage.options.map((o,i)=>`<button class="choice" data-answer="${i}"><span class="choice-icon">${String.fromCharCode(65+i)}</span><span class="choice-copy">${escapeHtml(o)}</span></button>`).join('')}</div><div id="gameFeedback" class="feedback"><span class="muted">Choisis une réponse.</span></div>`;host.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const correct=Number(b.dataset.answer)===stage.answer;host.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add(correct?'correct':'wrong');finishFeedback(prefix,stage,onSuccess,correct);}));}
function gameSingleVisual(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');host.innerHTML=`<div class="options-grid">${stage.visuals.map((o,i)=>`<button class="tile" data-answer="${i}"><span class="big">${escapeHtml(o[1])}</span><strong>${escapeHtml(o[0])}</strong><small>${escapeHtml(o[2])}</small></button>`).join('')}</div><div id="gameFeedback" class="feedback"><span class="muted">Compare les trois moitiés.</span></div>`;host.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const correct=Number(b.dataset.answer)===stage.answer;b.classList.add(correct?'correct':'wrong');finishFeedback(prefix,stage,onSuccess,correct);}));}
function gameMulti(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');const selected=new Set();const opts=stage.options.map((o,i)=>{const icon=Array.isArray(o)?o[0]:String.fromCharCode(65+i);const text=Array.isArray(o)?o[1]:o;return `<button class="choice" data-answer="${i}" aria-pressed="false"><span class="choice-icon">${escapeHtml(icon)}</span><span class="choice-copy">${escapeHtml(text)}</span></button>`}).join('');host.innerHTML=`<div class="options-grid">${opts}</div><button id="multiCheck" class="primary full">Vérifier ma sélection</button><div id="gameFeedback" class="feedback"><span class="muted">Plusieurs réponses peuvent être correctes.</span></div>`;host.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.answer);selected.has(i)?selected.delete(i):selected.add(i);b.classList.toggle('selected',selected.has(i));b.setAttribute('aria-pressed',selected.has(i));}));document.querySelector('#multiCheck').addEventListener('click',()=>finishFeedback(prefix,stage,onSuccess,exactArray([...selected],stage.correct)));}
function gameOrder(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');let order=shuffle(stage.items.map(x=>x[0]));if(exactArray(order,stage.correct)&&order.length>2)[order[0],order[1]]=[order[1],order[0]];const draw=()=>{host.innerHTML=`<div class="order-list">${order.map((id,i)=>{const item=stage.items.find(x=>x[0]===id);return `<div class="order-item"><span class="order-rank">${i+1}</span><span><strong>${escapeHtml(item[1])}</strong><small>${escapeHtml(item[2]||'')}</small></span><span class="order-controls"><button data-up="${i}" ${i===0?'disabled':''} aria-label="Monter">↑</button><button data-down="${i}" ${i===order.length-1?'disabled':''} aria-label="Descendre">↓</button></span></div>`}).join('')}</div><button id="orderCheck" class="primary full">Vérifier l’ordre</button><div id="gameFeedback" class="feedback"><span class="muted">Utilise les flèches pour déplacer les cartes.</span></div>`;host.querySelectorAll('[data-up]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.up);[order[i-1],order[i]]=[order[i],order[i-1]];draw()}));host.querySelectorAll('[data-down]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.down);[order[i+1],order[i]]=[order[i],order[i+1]];draw()}));document.querySelector('#orderCheck').addEventListener('click',()=>finishFeedback(prefix,stage,onSuccess,order.join('|')===stage.correct.join('|')));};draw();}
function gameSort(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');let active=null;const assignments={};const draw=()=>{const unassigned=stage.items.filter(x=>!assignments[x[0]]);host.innerHTML=`<div class="sort-board"><div><strong>Cartes à classer</strong><div class="sort-pool">${unassigned.map(x=>`<button class="sort-card ${active===x[0]?'active':''}" data-card="${x[0]}">${escapeHtml(x[1])}</button>`).join('')||'<span class="muted">Toutes les cartes sont placées.</span>'}</div></div><div class="sort-zones">${stage.zones.map(z=>`<section class="sort-zone" data-zone="${z[0]}"><h3>${escapeHtml(z[1])}</h3>${stage.items.filter(x=>assignments[x[0]]===z[0]).map(x=>`<button class="sort-card" data-card="${x[0]}">${escapeHtml(x[1])}</button>`).join('')}</section>`).join('')}</div><button id="sortCheck" class="primary full">Vérifier le classement</button><div id="gameFeedback" class="feedback"><span class="muted">Touche une carte, puis la catégorie choisie. Retouche une carte placée pour la déplacer.</span></div></div>`;host.querySelectorAll('[data-card]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.card;if(assignments[id])delete assignments[id];active=id;draw()}));host.querySelectorAll('[data-zone]').forEach(z=>z.addEventListener('click',e=>{if(e.target.closest('[data-card]')||!active)return;assignments[active]=z.dataset.zone;active=null;draw()}));document.querySelector('#sortCheck').addEventListener('click',()=>{const correct=stage.items.every(x=>assignments[x[0]]===x[2]);finishFeedback(prefix,stage,onSuccess,correct)});};draw();}
function gameMatch(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');host.innerHTML=`<div class="match-grid">${stage.sources.map(s=>`<label class="match-row"><span class="match-source">${escapeHtml(s[1])}</span><select data-source="${s[0]}"><option value="">Choisir…</option>${stage.targets.map(t=>`<option value="${t[0]}">${escapeHtml(t[1])}</option>`).join('')}</select></label>`).join('')}</div><button id="matchCheck" class="primary full">Vérifier les associations</button><div id="gameFeedback" class="feedback"><span class="muted">Chaque ligne doit recevoir une réponse.</span></div>`;document.querySelector('#matchCheck').addEventListener('click',()=>{const correct=stage.sources.every(s=>host.querySelector(`[data-source="${s[0]}"]`).value===stage.correct[s[0]]);finishFeedback(prefix,stage,onSuccess,correct)});}
function gameMap(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');let active=null;const assignments={};const draw=()=>{host.innerHTML=`<div class="map-board"><div class="river"></div>${stage.slots.map(s=>`<button class="map-slot ${assignments[s[0]]?'filled':''}" data-slot="${s[0]}" style="left:${s[2].left};top:${s[2].top}">${assignments[s[0]]?`${stage.tokens.find(t=>t[0]===assignments[s[0]])[3]} ${escapeHtml(stage.tokens.find(t=>t[0]===assignments[s[0]])[1])}`:escapeHtml(s[1])}</button>`).join('')}</div><div class="map-token-pool">${stage.tokens.filter(t=>!Object.values(assignments).includes(t[0])).map(t=>`<button class="map-token ${active===t[0]?'active':''}" data-token="${t[0]}">${t[3]} ${escapeHtml(t[1])}</button>`).join('')}</div><button id="mapCheck" class="primary full">Vérifier la carte</button><div id="gameFeedback" class="feedback"><span class="muted">Touche un repère, puis son emplacement sur la carte.</span></div>`;host.querySelectorAll('[data-token]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.token;draw()}));host.querySelectorAll('[data-slot]').forEach(s=>s.addEventListener('click',()=>{if(assignments[s.dataset.slot]){active=assignments[s.dataset.slot];delete assignments[s.dataset.slot];return draw()}if(!active)return;assignments[s.dataset.slot]=active;active=null;draw()}));document.querySelector('#mapCheck').addEventListener('click',()=>{const correct=stage.tokens.every(t=>assignments[t[2]]===t[0]);finishFeedback(prefix,stage,onSuccess,correct)});};draw();}
function gameRotate(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');let rotations=Array.from({length:9},()=>[0,90,180,270][Math.floor(Math.random()*4)]);if(rotations.every(x=>x===0))rotations[4]=90;const draw=()=>{host.innerHTML=`<div class="puzzle-grid">${rotations.map((r,i)=>`<button class="puzzle-piece" data-piece="${i}" style="--rot:${r}deg" aria-label="Faire pivoter la pièce ${i+1}"></button>`).join('')}</div><button id="puzzleCheck" class="primary full">Faire passer la lumière</button><div id="gameFeedback" class="feedback"><span class="muted">Toutes les étoiles doivent être droites.</span></div>`;host.querySelectorAll('[data-piece]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.piece);rotations[i]=(rotations[i]+90)%360;draw()}));document.querySelector('#puzzleCheck').addEventListener('click',()=>finishFeedback(prefix,stage,onSuccess,rotations.every(r=>r===0)));};draw();}
function gameMemorySequence(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');let phase='show';let order=shuffle(stage.sequence.map(x=>x[0]));const reveal=()=>{host.innerHTML=`<div class="memory-grid">${stage.sequence.map(x=>`<div class="memory-card revealed"><span>${x[1]}</span><small>${escapeHtml(x[2])}</small></div>`).join('')}</div><div class="notice info"><strong>Mémorise les quatre symboles</strong><p>Ils seront masqués dans quelques secondes.</p></div>`;setTimeout(()=>{phase='play';draw()},state.reducedMotion?1000:3200)};const draw=()=>{host.innerHTML=`<div class="order-list">${order.map((id,i)=>{const x=stage.sequence.find(s=>s[0]===id);return `<div class="order-item"><span class="order-rank">${i+1}</span><span><strong>${x[1]} ${escapeHtml(x[2])}</strong></span><span class="order-controls"><button data-up="${i}" ${i===0?'disabled':''}>↑</button><button data-down="${i}" ${i===order.length-1?'disabled':''}>↓</button></span></div>`}).join('')}</div><button id="memoryCheck" class="primary full">Vérifier ma mémoire</button><div id="gameFeedback" class="feedback"><span class="muted">Ordre demandé : ce qui soutient, ce qui ouvre, la lumière, l’ombre.</span></div>`;host.querySelectorAll('[data-up]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.up);[order[i-1],order[i]]=[order[i],order[i-1]];draw()}));host.querySelectorAll('[data-down]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.down);[order[i+1],order[i]]=[order[i],order[i+1]];draw()}));document.querySelector('#memoryCheck').addEventListener('click',()=>finishFeedback(prefix,stage,onSuccess,order.join('|')===stage.correct.join('|')));};reveal();}
function gameCollect(prefix,stage,onSuccess){const host=document.querySelector('#gameHost');const found=new Set();const draw=()=>{host.innerHTML=`<div class="notice info"><strong>Range le téléphone entre deux repères</strong><p>Cette épreuve sert à regarder la ville, pas à rester devant l’écran.</p></div><div class="collect-grid">${stage.items.map(x=>`<button class="collect-card ${found.has(x[0])?'found':''}" data-found="${x[0]}"><span>${x[2]}</span>${escapeHtml(x[1])}${found.has(x[0])?'<small>Reconnu ✓</small>':''}</button>`).join('')}</div><button id="collectCheck" class="primary full">Valider ${found.size}/${stage.required}</button><div id="gameFeedback" class="feedback"><span class="muted">Quatre repères suffisent pour réussir.</span></div>`;host.querySelectorAll('[data-found]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.found;found.has(id)?found.delete(id):found.add(id);draw()}));document.querySelector('#collectCheck').addEventListener('click',()=>finishFeedback(prefix,stage,onSuccess,found.size>=stage.required));};draw();}

function renderEvidence(){appHeader('Dossier des preuves');const cards=MISSIONS.map((m,i)=>`<article class="evidence-card ${state.proofs.includes(m.id)?'':'locked'}"><span class="seal-mark">${state.proofs.includes(m.id)?m.sealIcon:'?'}</span><strong>${escapeHtml(m.title)}</strong><small>${state.proofs.includes(m.id)?escapeHtml(m.proof):'Preuve encore masquée'}</small></article>`).join('');screenWrap(`<article class="card stack"><div class="eyebrow">Dossier d’enquête</div><h1 class="screen-title">Les preuves authentifiées</h1><p>Chaque conclusion repose sur un lieu observé et un raisonnement historique.</p></article><div class="evidence-grid">${cards}</div>`);}
function renderInventory(){appHeader('Collection de l’enquêtrice');const cards=MISSIONS.map(m=>`<article class="inventory-card ${state.items.includes(m.id)?'':'locked'}"><span class="seal-mark">${state.items.includes(m.id)?m.sealIcon:'?'}</span><strong>${state.items.includes(m.id)?escapeHtml(m.item):'Objet verrouillé'}</strong><small>${escapeHtml(m.place)}</small></article>`).join('');screenWrap(`<article class="card stack"><div class="eyebrow">Blason de progression</div><h1 class="screen-title">Sceaux et objets</h1>${progressHeader('Collection complétée',state.items.length,8)}<div class="stars">${'★'.repeat(state.completed.length)}${'☆'.repeat(8-state.completed.length)}</div></article><div class="inventory-grid">${cards}</div>`);}
function renderHelp(){appHeader('Aide et informations');screenWrap(`<article class="card stack"><div class="eyebrow">Mode d’emploi</div><h1 class="screen-title">Jouer sur place</h1><div class="notice info"><strong>Le téléphone reste dans les mains d’un adulte</strong><p>L’enfant observe d’abord le lieu réel, puis utilise l’application pour résoudre l’énigme.</p></div><h2>Les indices</h2><p>Chaque épreuve propose trois aides progressives. Elles n’empêchent jamais d’obtenir le sceau.</p><h2>Lieu inaccessible</h2><p>Le mode adulte permet d’ouvrir ou de valider une mission. Le mode mission courte conserve une seule énigme essentielle par lieu.</p><h2>Respect des lieux</h2><p>Dans la cathédrale et les musées, gardez le téléphone silencieux, ne touchez pas les œuvres et respectez les consignes du personnel.</p><h2>Données et connexion</h2><p>La progression est enregistrée uniquement dans le navigateur. Après le premier chargement, l’application fonctionne hors connexion.</p><h2>Repères historiques intégrés</h2><p>Le jeu distingue les événements de 1429, les traces liées aux lieux et les œuvres de mémoire réalisées plus tard. Les repères sont issus des ressources patrimoniales officielles de la Ville et de la Métropole d’Orléans.</p></article>`);}

function renderFinal(){if(state.completed.length<8&&!state.finalUnlocked){toast('Il faut réunir les huit sceaux.');return setScreen('map')}appHeader('Tribunal de la Chronique');if(state.finalDone)return setScreen('certificate');const idx=state.finalStage||0;if(idx>=FINAL_STAGES.length)return renderFinalCinematic();const stage=FINAL_STAGES[idx];screenWrap(`<article class="card stack"><div class="mission-kicker"><span class="pill dark">Tribunal final</span><span class="pill">${idx+1}/${FINAL_STAGES.length}</span></div><div class="brouilleur-strip"><img src="assets/brouilleur.svg" alt=""><p><strong>Le Brouilleur :</strong> « Tu ne sauras jamais distinguer mes fausses histoires des vraies ! »</p></div>${progressHeader('Jugement des preuves',idx+1,FINAL_STAGES.length)}<div class="eyebrow">Manche ${idx+1}</div><h1 class="screen-title">${escapeHtml(stage.title)}</h1><p>${escapeHtml(stage.instruction)}</p><div id="gameHost" class="game-board"></div><div class="hint-actions"><button id="hintBtn">Indice 1</button><button id="finalExit">Retour au parcours</button></div><div id="hintBox" class="hint-box"><span class="muted">Aucun indice utilisé.</span></div></article>`);renderGame('final',stage,()=>{state.finalStage=idx+1;saveState();renderFinal()});renderHint('final',stage);document.querySelector('#hintBtn').addEventListener('click',()=>useHint('final',stage));document.querySelector('#finalExit').addEventListener('click',()=>setScreen('map'));}
function renderFinalCinematic(){screenWrap(`<article class="card reward stack"><img src="assets/brouilleur.svg" alt="Le Brouilleur d’Encre devient conteur de légendes" style="width:min(100%,440px);margin:auto;border-radius:18px"><div class="eyebrow">Le Grand Livre est restauré</div><h1 class="screen-title">Le Brouilleur reconnaît sa défaite</h1><div class="speech-bubble"><p>« Très bien… J’écrirai l’histoire d’un dragon qui mangeait les remparts, mais je préciserai que c’est une légende ! »</p></div><div class="parchment"><p><strong>JEANNE D’ARC ENTRE À ORLÉANS LE 29 AVRIL 1429. ELLE PARTICIPE AUX COMBATS. LE SIÈGE EST LEVÉ LE 8 MAI 1429.</strong></p></div><button id="titleBtn" class="primary">Recevoir mon titre</button></article>`);celebrate();document.querySelector('#titleBtn').addEventListener('click',()=>{state.finalDone=true;saveState();setScreen('certificate')});}
function renderCertificate(){appHeader('Diplôme de l’enquêtrice');const totalAttempts=Object.values(state.attempts).reduce((a,b)=>a+b,0);const hints=Object.values(state.hints).reduce((a,b)=>a+b,0);const first=Object.values(state.missionStats).reduce((a,b)=>a+(b.correctFirst||0),0);screenWrap(`<article class="certificate card"><div class="eyebrow">Grand Livre d’Orléans</div><h1>Diplôme d’Enquêtrice de la Chronique</h1><p>Décerné à</p><div class="certificate-name">${escapeHtml(state.name)}</div><p>pour avoir authentifié les huit preuves, déjoué les anachronismes du Brouilleur et restauré la chronologie du siège de 1429.</p><h2>Gardienne des huit Sceaux de Vérité</h2><div class="certificate-seals">${MISSIONS.map(m=>`<span title="${escapeHtml(m.seal)}">${m.sealIcon}</span>`).join('')}</div><div class="score-row"><div class="score-box"><strong>${first}</strong><small>réussites immédiates</small></div><div class="score-box"><strong>${hints}</strong><small>indices utilisés</small></div><div class="score-box"><strong>${totalAttempts}</strong><small>tentatives</small></div></div><p><strong>Orléans · ${new Intl.DateTimeFormat('fr-FR',{dateStyle:'long'}).format(new Date())}</strong></p><div class="no-print stack"><button id="printBtn" class="primary">Imprimer ou enregistrer le diplôme</button><button id="reviewBtn" class="secondary">Revoir les preuves</button></div></article>${state.hasLittle?`<article class="card center"><div class="seal-mark" style="margin:auto">🚩</div><h2>Éclaireuse des couleurs et des formes</h2><p>Ce titre est attribué à <strong>${escapeHtml(state.littleName||'la petite éclaireuse')}</strong> pour avoir aidé à retrouver chevaux, couleurs, ponts, briques et arches.</p></article>`:''}`);document.querySelector('#printBtn').addEventListener('click',()=>window.print());document.querySelector('#reviewBtn').addEventListener('click',()=>setScreen('evidence'));}

// Navigation, settings and installation
bottomNav.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)setScreen(b.dataset.nav)});
document.querySelector('#homeBtn').addEventListener('click',()=>setScreen('home'));
document.querySelector('#settingsBtn').addEventListener('click',()=>settingsDialog.showModal());
document.querySelector('#fatigueToggle').addEventListener('change',e=>{state.fatigue=e.target.checked;Object.keys(state.missionStage).forEach(k=>state.missionStage[k]=0);saveState();toast(state.fatigue?'Mode mission courte activé':'Parcours complet activé')});
document.querySelector('#speechToggle').addEventListener('change',e=>{state.speech=e.target.checked;saveState()});
document.querySelector('#motionToggle').addEventListener('change',e=>{state.reducedMotion=e.target.checked;saveState()});
document.querySelector('#contrastSelect').addEventListener('change',e=>{state.contrast=e.target.value;saveState()});
document.querySelector('#adultModeBtn').addEventListener('click',()=>{settingsDialog.close();populateAdult();adultDialog.showModal()});
function populateAdult(){const s=document.querySelector('#adultMissionSelect');s.innerHTML=MISSIONS.map((m,i)=>`<option value="${i}">${i+1}. ${escapeHtml(m.title)}</option>`).join('');s.value=String(state.activeMission)}
document.querySelector('#adultOpenBtn').addEventListener('click',()=>{state.activeMission=Number(document.querySelector('#adultMissionSelect').value);saveState();adultDialog.close();setScreen('mission',{index:state.activeMission})});
document.querySelector('#adultCompleteBtn').addEventListener('click',()=>{const i=Number(document.querySelector('#adultMissionSelect').value);const m=MISSIONS[i];if(!state.completed.includes(m.id)){state.completed.push(m.id);state.seals.push(m.id);state.items.push(m.id);state.proofs.push(m.id)}state.missionStage[m.id]=effectiveStages(m).length;state.activeMission=Math.min(i+1,7);saveState();toast('Mission validée par le mode adulte');populateAdult()});
document.querySelector('#adultFinalBtn').addEventListener('click',()=>{state.finalUnlocked=true;saveState();adultDialog.close();setScreen('final')});
document.querySelector('#adultResetBtn').addEventListener('click',()=>{adultDialog.close();document.querySelector('#confirmTitle').textContent='Réinitialiser l’aventure ?';document.querySelector('#confirmText').textContent='Toute la progression enregistrée sur cet appareil sera effacée.';confirmDialog.showModal()});
document.querySelector('#confirmAction').addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);state=defaultState();confirmDialog.close();setScreen('home')});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;document.querySelector('#installBtn').hidden=false});
document.querySelector('#installBtn').addEventListener('click',async()=>{if(!deferredInstallPrompt)return toast('Utilisez le menu du navigateur pour ajouter l’application à l’écran d’accueil.');deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;document.querySelector('#installBtn').hidden=true});
window.addEventListener('appinstalled',()=>toast('Application installée'));

if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
applySettings();
setScreen(state.started?(state.prologueSeen?'home':'prologue'):'home');
